### ISSUE TITLE
how do I bash / sh to the container?

### ISSUE THREAD

**Issue by shiroamada** [p13eater/docker-apache-php#2]
how do I bash / sh to the container?
I mount the volume, but I can't access, how do I troubleshoot it and check for it? and how do I update the apache configuration?

**Comment by craig-mcmahon** [comment]
Hi,

bash is not installed on this image, but you can use sh

To sh into an already running container you can use something like

```
docker exec -it CONTAINER_NAME sh
```

You can add custom apache configurations in the `/etc/apache2/conf.d/custom` directory

**Comment by shiroamada** [comment]
Excellent! Thanks for your help!
