### ISSUE TITLE
how do I restart the apache service after allow .htaccess

### ISSUE THREAD

**Issue by shiroamada** [p13eater/docker-apache-php#3]
after I edit the **/etc/apache/httpd.conf**
set the 
`AllowOverride None`
to
`AllowOverride All`

now do I restart the apache server?

Sorry I am newly in docker.

**Comment by craig-mcmahon** [comment]
Hi,

If you restart the container, that will restart the apache server, but if you have been editing files directly in the container, those changes could be lost. If you need to replace/update any files or packages please ensure you create your own container from this image.

Please see https://docs.docker.com/engine/reference/builder/ for more information

**Comment by shiroamada** [comment]
Ok, I think I will do a git clone from your project, and edit accordingly the Dockerfile. 

I added below line
`&& sed -i -e 's/AllowOverride None/AllowOverride All/g' /etc/apache2/httpd.conf \`

and build my own image
`docker build -t my-apache-php:latest . `

Thanks!
